project:
  type: website
  resources:
    - downloads/index.pdf
website:
  title: "Guías de Laboratorio"
  navbar:
    left:
      - text: "Inicio"
        file: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    include-after-body: includes/footer.html
  pdf:
    documentclass: article
    toc: true

